{% set name = "bowler" %}
{% set version = "0.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3e0ba2e6d62d84e9dc34c07fd4ae6453c8de480e14cdd67a5665cfeedbf8cb2

build:
  noarch: python
  number: 0
  entry_points:
    - bowler = bowler.main:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=38.6.0
  run:
    - attrs
    - click
    - fissix
    - python
    - sh

test:
  imports:
    - bowler
    - bowler.tests
  commands:
    - bowler --help
    - python -m unittest -v bowler.tests

about:
  home: https://pybowler.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Safe code refactoring for modern Python projects
  dev_url: https://github.com/facebookincubator/bowler

extra:
  recipe-maintainers:
    - nicoddemus
