travis:
  secure:
    BINSTAR_TOKEN: Mi1UH3feBQo0PyVE2W/9LDge7EkjlNyh8rt62QiFFk5q/VXVIBYC9y/VvD3q5eglRWJQ9zdsp5QP5+bdx4OEvYl6P/r075TqMWwZRwKc0kl6nmcVjidd6tN5GeXeZeRyelQ+TQhUS8VZqkeL/qC7O45fCB1j+cVa/e0SoUmasl7qjFWWWEMbogfxYPBXzccXOqoG199NJ9tDb3iIN/81wAu2y7Qbs0AAeFUq//iMt7wDQudPXFppwau8x6yPMAH4jLebrafhfC4pMSdtnGRohuqCpeInXRvEI+SOFBtfRNQyfrjJDtb+ZDcUSCdXchZw46YorDt5kT2y171YUFVrfJjvkuvIv6xl3FzLLdo2QZHJwU5Vt/nIueIPy3ZkYkIl8hbhz69dSsrVvbf4MDYtFkyGE14GSyMUPmoZ+4+1ntjM8WskL7SjLU5NyOKkWOS4Ova+ATIxpaUO3ypMeB3Q6hsrXfCsWtOcm10wDIrmWZ+LZw4eLdlyKWYIMrG/hm+iUreioo+3tvpzAB/xDMdruhti5VW9OFDkwQdzIPk8GXrHZEGkKADl3LqLA/Ylw8Na/Hh00PqgwxPGgswscG/gyXeeHmRaEibteAqF5SzCqsjK3ioJ1AU6vxlb1PvfS3ElIwsibn6X4lpVBRITOxY/nwVD/yY69In+CmkgYKRzu/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
